# Dev configuaration
replicaCount: 2

env:
  - name: SECRET_KEY
    value: ProdHelmChartSecret

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: prod-testserver-testserver-stripprefix@kubernetescrd
  hosts:
    - host: testserver.gerull.nl
      paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80