{{- if and .Values.ingress.enabled .Values.ingress.className }}
{{- if eq .Values.ingress.className "traefik" }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "testserver.name" . }}-stripprefix
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
    {{- range .Values.ingress.hosts }}
      {{- range .paths }}
        - "{{ .path }}"
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}