apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    argocd_environment: sse_test
  name: sse-test
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Share Services Test deploy project
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
