variables:
  CHART: testserver
  SCRIPTS_REPO: https://$SCRIPTS_USER:$SCRIPTS_TOKEN@gitlab.com/cgerull-orchestration/ci-scripts
  YQ_VERSION: v4.24.2
  YQ_BINARY: yq_linux_amd64
before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - curl -L https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz > ${YQ_BINARY}.tar.gz
  - tar -zxf ${YQ_BINARY}.tar.gz
  - chmod +x ${YQ_BINARY} && mv ${YQ_BINARY} /usr/bin/yq

# default:
#   tags:
#     - ubuntu

stages:
  - build
  - test
  - publish

build-chart-package:
  stage: "build"
  variables:
    CHART: testserver
  script:
    - echo "CI_COMMIT_REF_NAME ${CI_COMMIT_REF_NAME}"
    - echo "CI_COMMIT_TAG ${CI_COMMIT_TAG}"
    - echo "CI_PIPELINE_IID ${CI_PIPELINE_IID}"
    - echo "CI_PIPELINE_SOURCE ${CI_PIPELINE_SOURCE}"
    # - echo "PWD $(ls -lisa)"
    # - echo "TMP $(ls -lisa ${SCRIPTS_DIR})"
    # - echo "bin $(ls -lisa /bin)"
    # - echo "usrbin $(ls -lisa /usr/bin)"
    # - echo "env $(env)"
    # - helm version
    # - yq version
    - ${SCRIPTS_DIR}/build/build-helm-package.sh ${CHART} ${CI_PIPELINE_IID}
  only:
    - optimize-for-argocd
  artifacts:
    paths:
    - ${CHART}-*.tgz
    expire_in: 1 week

generate-manifests:
  stage: build
  script:
     - ${SCRIPTS_DIR}/build/generate-kubernetes-manifests.sh ${CHART} dev
  only:
    - optimize-for-argocd

test-manifests:
  stage: "test"
  script:
    - ${SCRIPTS_DIR}/test/test-kubernetes-manifests.sh ${CHART} dev
  only:
    - optimize-for-argocd

publish-helm-chart:
  # image: curlimages/curl:latest
  variables:
    CHANNEL: "stable"
  needs:
    - build-chart-package
  stage: publish
  script:
    - |
      for file in $(${CHART}-*.tgz); do
        echo "Upload ${file} to ${CI_API_V4_URL}"
        curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${file}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${CHANNEL}/charts"
      done