variables:
  CHART: testserver
  SCRIPTS_REPO: https://gitlab.solvinity.net/shared-services/docker/scripts/ci-scripts
before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"

default:
  tags:
    - sse-docker

stages:
  - build
  - test

build-chart-package:
  stage: "build"
  variables:
    CHART: testserver
  script:
    - echo "CI_COMMIT_REF_NAME ${CI_COMMIT_REF_NAME}"
    - echo "CI_COMMIT_TAG ${CI_COMMIT_TAG}"
    - echo "CI_PIPELINE_IID ${CI_PIPELINE_IID}"
    - echo "CI_PIPELINE_SOURCE ${CI_PIPELINE_SOURCE}"
    - ${SCRIPTS_DIR}/build/build-helm.sh charts/${CHART} ${CI_PIPELINE_IID}
  only:
    - optimize-for-argocd
  artifacts:
    paths:
    - ${CHART}-*.tgz
    expire_in: 1 week

generate-manifests:
  stage: build
  script:
     - ${SCRIPTS_DIR}/build/generate-kubernetes-manifests.sh charts/${CHART} dev
  only:
    - optimize-for-argocd

test-manifests:
  stage: "test"
  script:
    - ${SCRIPTS_DIR}/build/test-kubernetes-manifests.sh charts/${CHART} dev
  only:
    - optimize-for-argocd
