variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  tags:
    - sse-docker

stages:
  - build
  - manifests
  - push-acc


build-package:
  stage: "build"
  script:
    - .cicd/build.sh
  only:
    - optimize-for-argocd
  artifacts:
    paths:
    - *.tgz
    expire_in: 1 week

build-manifests:
  stage: manifests
  script:
    - .cicd/build-manifests.sh
  only:
    - optimize-for-argocd

push-package-acc:
  stage: "push-acc"
  script:
    - .cicd/push-acc.sh
  only:
    - optimize-for-argocd
