variables:
  SCRIPTS_REPO: https://gitlab.solvinity.net/shared-services/docker/scripts/ci-scripts
before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"
  - echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"
  - echo "CI_COMMIT_TAG: ${CI_COMMIT_TAG}"
  - echo "CI_PIPELINE_IID: ${CI_PIPELINE_IID}"
  - echo "CI_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}"

default:
  tags:
    - sse-docker

stages:
  - build
  - manifests
  - push-acc


build-chart-package:
  stage: "build"
  variables:
    CHART: testserver
  script:
    - ${SCRIPTS_DIR}/build/build-helm.sh charts/${CHART} ${CI_PIPELINE_IID}
  only:
    - optimize-for-argocd
  artifacts:
    paths:
    - ${CHART}-*.tgz
    expire_in: 1 week

generate-manifests:
  stage: build
  script:
    - .cicd/build-manifests.sh
  only:
    - optimize-for-argocd

push-package-acc:
  stage: "push-acc"
  script:
    - .cicd/push-acc.sh
  only:
    - optimize-for-argocd
