version: "3.9"
   
services:
  db:
    image: mariadb:10.7-focal
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssW0rd
      - MARIADB_USER=testserver
      - MARIADB_PASSWORD=my_cool_secret
    volumes:
      - ./data/db:/var/lib/mysql
  web:
    image: cgerull/testserver:0.9.1
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=DockerComposeSecret
    depends_on:
      - db