version: "3.9"
   
services:
  db:
    image: mariadb:10.7-focal
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssW0rd
      - MARIADB_USER=testserver
      - MARIADB_PASSWORD=my_cool_secret
    volumes:
      - ./data/db:/var/lib/mysql
  redis: 
    image: redis:alpine3.15
  web:
    image: cgerull/testserver:latest
    ports:
      - "4080:8080"
    environment:
      - SECRET_KEY=DockerComposeSecret
      - REDIS_SERVER=redis
    depends_on:
      - redis
      - db