apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: demo-vault-example
spec:
  secretStoreRef:
    name: demo-vault-backend
    kind: SecretStore
  target:
    name: demo-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: local/demo/secret
      property: password